SCORE_LAMBDA_FOUND = 25
SCORE_ABORT_BONUS  = 25
SCORE_WIN_BONUS    = 50
SCORE_STEP_COST    = 1

DEFAULT_WATER = 0
DEFAULT_FLOOD = 0
DEFAULT_PROOF = 10
DEFAULT_GROWTH = 25
DEFAULT_RAZORS = 0
DEFAULT_TRAMPOS = []

CMD_LEFT  = "L"
CMD_RIGHT = "R"
CMD_DOWN  = "U"
CMD_UP    = "D"
CMD_WAIT  = "W"
CMD_ABORT = "A"
CMD_SHAVE = "S"

ORD_ROBOT = 82
ORD_CLOSED_LIFT = 76
ORD_OPEN_LIFT = 79
ORD_LAMBDA = 92
